spring.application.name=api-gateway
server.port=8765

# 1. Explicitly map the Quiz Service
spring.cloud.gateway.server.webmvc.routes[0].id=quiz-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/quiz-service/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# 2. Explicitly map the Question Service
spring.cloud.gateway.server.webmvc.routes[1].id=question-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/question-service/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1